### ISSUE TITLE
Instructions inaccurate/incomplete

### ISSUE THREAD

**Issue by mikes1979** [ragingdave/simplersaml#1]
Service provider string is invalid.  Your instructions are incomplete or wrong, as adding your string to service providers does not work as expected.

**Comment by ragingdave** [comment]
If you can supply more information I would be glad to help. When you say the "Service Provider string is invalid" what do you mean. Are there any errors associated with the failure?

**Comment by VickG** [comment]
Service provider string usually end in ::class

**Comment by ragingdave** [comment]
Updated the install instructions to reflect new installation instructions for service providers.

**Comment by VickG** [comment]
that was quick, thanks!

**Comment by ragingdave** [comment]
:)
