### ISSUE TITLE
cannot add your library, getting following error

### ISSUE THREAD

**Issue by VickG** [ragingdave/simplersaml#2]
okta@dmdev:~/public_html$ composer require ragingdave/simplersaml:dev-master
./composer.json has been updated

> php artisan clear-compiled
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ragingdave/simplersaml dev-master -> satisfiable by ragingdave/simplersaml[dev-master].
    - Conclusion: remove laravel/framework v5.1.19
    - Conclusion: don't install laravel/framework v5.1.19
    - ragingdave/simplersaml dev-master requires illuminate/support 5.0.\* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5.1.19
    - don't install illuminate/support v5.0.22|don't install laravel/framework v5.1.19
    - don't install illuminate/support v5.0.25|don't install laravel/framework v5.1.19
    - don't install illuminate/support v5.0.26|don't install laravel/framework v5.1.19
    - don't install illuminate/support v5.0.28|don't install laravel/framework v5.1.19
    - don't install illuminate/support v5.0.33|don't install laravel/framework v5.1.19
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5.1.19
    - Installation request for laravel/framework == 5.1.19.0 -> satisfiable by laravel/framework[v5.1.19].

Installation failed, reverting ./composer.json to its original content.

**Comment by ragingdave** [comment]
I have updated the constraint for laravel to be ~5.0 which should allow you to at least install it now.

**Comment by VickG** [comment]
please close this isue, confirming it's working fine after constrain update.
